"""add audit entry columns to audit_logs

Revision ID: 2a52a1908f9a
Revises: 3abdfd696724
Create Date: 2026-07-28 19:00:15.825741

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2a52a1908f9a"
down_revision: Union[str, Sequence[str], None] = "3abdfd696724"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Adiciona as colunas de AuditEntry (orchestrator/state.py, CLAUDE.md seção
    10) ainda ausentes em audit_logs: actor, module, tokens_used, duration_ms
    e metadata. A tabela nunca recebeu INSERTs até agora (nenhum código do
    repositório grava em audit_logs ainda), então as colunas NOT NULL sem
    server_default (actor, module) não quebram nenhuma linha existente.

    Diferente de CREATE TABLE (que cria os ENUMs referenciados
    automaticamente), ADD COLUMN não cria o tipo — precisa ser feito à mão
    antes de referenciá-lo na coluna.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    audit_actor = postgresql.ENUM("system", "agent", "human", name="audit_actor")
    audit_actor.create(op.get_bind(), checkfirst=True)
    module_name = postgresql.ENUM(
        "intake", "evidence", "research", "strategy", "drafting", "review", name="module_name"
    )
    module_name.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "audit_logs",
        sa.Column("actor", audit_actor, nullable=False),
    )
    op.add_column(
        "audit_logs",
        sa.Column("module", module_name, nullable=False),
    )
    op.add_column(
        "audit_logs", sa.Column("tokens_used", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column(
        "audit_logs", sa.Column("duration_ms", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column(
        "audit_logs",
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("audit_logs", "metadata")
    op.drop_column("audit_logs", "duration_ms")
    op.drop_column("audit_logs", "tokens_used")
    op.drop_column("audit_logs", "module")
    op.drop_column("audit_logs", "actor")
    # ### end Alembic commands ###

    # DROP TABLE/COLUMN não apaga os tipos ENUM nativos — ficam órfãos e
    # quebram um próximo upgrade ("type already exists"), igual ao padrão já
    # usado na migration 0406e102877a.
    op.execute("DROP TYPE IF EXISTS module_name")
    op.execute("DROP TYPE IF EXISTS audit_actor")
