"""add case_checkpoints table

Revision ID: e5c113039c58
Revises: 2a52a1908f9a
Create Date: 2026-07-28 19:19:12.659142

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e5c113039c58"
down_revision: Union[str, Sequence[str], None] = "2a52a1908f9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_TENANT_ISOLATION_EXPR = "NULLIF(current_setting('app.current_tenant', true), '')::uuid"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "case_checkpoints",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("step", sa.Integer(), nullable=False),
        sa.Column("current_module", sa.String(length=20), nullable=False),
        sa.Column("state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", "step", name="uq_case_checkpoints_case_id_step"),
    )
    op.create_index(
        op.f("ix_case_checkpoints_case_id"), "case_checkpoints", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_case_checkpoints_tenant_id"), "case_checkpoints", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###

    # --- Row Level Security (mesmo padrão de 0406e102877a/3abdfd696724) ---
    op.execute("ALTER TABLE case_checkpoints ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE case_checkpoints FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation ON case_checkpoints "
        f"USING (tenant_id = {_TENANT_ISOLATION_EXPR}) "
        f"WITH CHECK (tenant_id = {_TENANT_ISOLATION_EXPR})"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON case_checkpoints")
    op.execute("ALTER TABLE case_checkpoints NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE case_checkpoints DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_case_checkpoints_tenant_id"), table_name="case_checkpoints")
    op.drop_index(op.f("ix_case_checkpoints_case_id"), table_name="case_checkpoints")
    op.drop_table("case_checkpoints")
    # ### end Alembic commands ###
